### PR TITLE
feat(domains): add endpoint that verifies and returns a single domain

### PR DESCRIPTION
**Pull request by rainerborene**
Add missing API endpoint that verifies and returns a single domain. As seen here: https://documentation.mailgun.com/en/latest/api-domains.html#domains

### CODE REVIEW

**Comment by rainerborene** [comment]
ping @timcraft

**Comment by timcraft** [comment]
@rainerborene Merged, thanks!

**Comment by rainerborene** [comment]
@timcraft I forgot to update the changelog and one more thing... could you release a new version on rubygems?

**Comment by timcraft** [comment]
@rainerborene You don't need to update the changelog, that's part of the release process.

I'll release a new version when I find the time to do some releases.

**Pull request merged**
